system_packages:
  - gcc
  - glibc
  - glibc-common
  - wget
  - unzip
  - httpd
  - php
  - gd
  - gd-devel
  - perl
  - postfix
  - make
  - gettext
  - automake
  - autoconf
  - openssl-devel
  - net-snmp
  - net-snmp-utils
apache_service: httpd
apache_conf_dir: /etc/httpd/conf.d